export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';

export const ALL_EMP_REQUEST = 'ALL_EMP_REQUEST';
export const ALL_EMP_CLEAR = 'ALL_EMP_CLEAR';
export const ALL_EMP_SUCCESS = 'ALL_EMP_SUCCESS';
export const ALL_EMP_ERROR = 'ALL_EMP_ERROR';

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_CLEAR = 'CHANGE_PASSWORD_CLEAR';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';

export const GET_ASSIGNED_INV_REQUEST = 'GET_ASSIGNED_INV_REQUEST';
export const GET_ASSIGNED_INV_CLEAR = 'GET_ASSIGNED_INV_CLEAR';
export const GET_ASSIGNED_INV_SUCCESS = 'GET_ASSIGNED_INV_SUCCESS';
export const GET_ASSIGNED_INV_ERROR = 'GET_ASSIGNED_INV_ERROR';

export const ADD_INV_REQUEST = 'ADD_INV_REQUEST';
export const ADD_INV_CLEAR = 'ADD_INV_CLEAR';
export const ADD_INV_SUCCESS = 'ADD_INV_SUCCESS';
export const ADD_INV_ERROR = 'ADD_INV_ERROR';

export const EDIT_INV_REQUEST = 'EDIT_INV_REQUEST';
export const EDIT_INV_CLEAR = 'EDIT_INV_CLEAR';
export const EDIT_INV_SUCCESS = 'EDIT_INV_SUCCESS';
export const EDIT_INV_ERROR = 'EDIT_INV_ERROR';

export const ADD_MY_INV_REQUEST = 'ADD_MY_INV_REQUEST';
export const ADD_MY_INV_CLEAR = 'ADD_MY_INV_CLEAR';
export const ADD_MY_INV_SUCCESS = 'ADD_MY_INV_SUCCESS';
export const ADD_MY_INV_ERROR = 'ADD_MY_INV_ERROR';

export const ALL_INV_REQUEST = 'ALL_INV_REQUEST';
export const ALL_INV_CLEAR = 'ALL_INV_CLEAR';
export const ALL_INV_SUCCESS = 'ALL_INV_SUCCESS';
export const ALL_INV_ERROR = 'ALL_INV_ERROR';

export const ASSIGN_INV_REQUEST = 'ASSIGN_INV_REQUEST';
export const ASSIGN_INV_CLEAR = 'ASSIGN_INV_CLEAR';
export const ASSIGN_INV_SUCCESS = 'ASSIGN_INV_SUCCESS';
export const ASSIGN_INV_ERROR = 'ASSIGN_INV_ERROR';

export const CREATE_AUDIT_REQUEST = 'CREATE_AUDIT_REQUEST';
export const CREATE_AUDIT_CLEAR = 'CREATE_AUDIT_CLEAR';
export const CREATE_AUDIT_SUCCESS = 'CREATE_AUDIT_SUCCESS';
export const CREATE_AUDIT_ERROR = 'CREATE_AUDIT_ERROR';

export const GET_AUDIT_REQUEST = 'GET_AUDIT_REQUEST';
export const GET_AUDIT_CLEAR = 'GET_AUDIT_CLEAR';
export const GET_AUDIT_SUCCESS = 'GET_AUDIT_SUCCESS';
export const GET_AUDIT_ERROR = 'GET_AUDIT_ERROR';

export const GET_UNAUDITED_REQUEST = 'GET_UNAUDITED_REQUEST';
export const GET_UNAUDITED_CLEAR = 'GET_UNAUDITED_CLEAR';
export const GET_UNAUDITED_SUCCESS = 'GET_UNAUDITED_SUCCESS';
export const GET_UNAUDITED_ERROR = 'GET_UNAUDITED_ERROR';

export const GET_UNASSIGNED_INV_REQUEST = 'GET_UNASSIGNED_INV_REQUEST';
export const GET_UNASSIGNED_INV_CLEAR = 'GET_UNASSIGNED_INV_CLEAR';
export const GET_UNASSIGNED_INV_SUCCESS = 'GET_UNASSIGNED_INV_SUCCESS';
export const GET_UNASSIGNED_INV_ERROR = 'GET_UNASSIGNED_INV_ERROR';

export const GET_REQUIREMENT_REQUEST = 'GET_REQUIREMENT_REQUEST';
export const GET_REQUIREMENT_CLEAR = 'GET_REQUIREMENT_CLEAR';
export const GET_REQUIREMENT_SUCCESS = 'GET_REQUIREMENT_SUCCESS';
export const GET_REQUIREMENT_ERROR = 'GET_REQUIREMENT_ERROR';

export const APPROVE_REQUIREMENT_REQUEST = 'APPROVE_REQUIREMENT_REQUEST';
export const APPROVE_REQUIREMENT_CLEAR = 'APPROVE_REQUIREMENT_CLEAR';
export const APPROVE_REQUIREMENT_SUCCESS = 'APPROVE_REQUIREMENT_SUCCESS';
export const APPROVE_REQUIREMENT_ERROR = 'APPROVE_REQUIREMENT_ERROR';

export const ADD_REQUIREMENT_REQUEST = 'ADD_REQUIREMENT_REQUEST';
export const ADD_REQUIREMENT_CLEAR = 'ADD_REQUIREMENT_CLEAR';
export const ADD_REQUIREMENT_SUCCESS = 'ADD_REQUIREMENT_SUCCESS';
export const ADD_REQUIREMENT_ERROR = 'ADD_REQUIREMENT_ERROR';